# Generated by Django 3.1.2 on 2020-11-04 14:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Infopart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boards',
            name='hire_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
