# Generated by Django 3.1.2 on 2020-11-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Infopart', '0004_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='post_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
